CREATE TABLE USERS(ID INT PRIMARY KEY, CIVILITY_ID INT, BUSINESS_ID INT, BIRTH_DATE DATE, CREATION_DATE DATE);
CREATE TABLE PROFILE_VALUE(ID INT PRIMARY KEY, USER_ID INT, IS_HISTO BOOLEAN, DOUBLE_VALUE DOUBLE, VAR_NAME VARCHAR(255));
CREATE TABLE CIVILITY(ID INT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BUSINESS_UNIT(ID INT PRIMARY KEY, CODE VARCHAR(255), CATEGORY VARCHAR(255));
